package com.dingzhang.model;
import java.util.Date;

public class EnterpriseWithBLOBs extends Enterprise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.question1
     *
     * @mbggenerated
     */
    private String question1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.question2
     *
     * @mbggenerated
     */
    private String question2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.question3
     *
     * @mbggenerated
     */
    private String question3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.question4
     *
     * @mbggenerated
     */
    private String question4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.question5
     *
     * @mbggenerated
     */
    private String question5;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public EnterpriseWithBLOBs(Integer id, Double lng, String name, Double lat, Integer level, String leader, String call_leader, String photo_leader, String member, String call_member, String photo_member, String boss, String call_boss, String photo_boss, Integer type, Date deadline, String description, String question1, String question2, String question3, String question4, String question5) {
        super(id, lng, name, lat, level, leader, call_leader, photo_leader, member, call_member, photo_member, boss, call_boss, photo_boss, type, deadline);
        this.description = description;
        this.question1 = question1;
        this.question2 = question2;
        this.question3 = question3;
        this.question4 = question4;
        this.question5 = question5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public EnterpriseWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.description
     *
     * @return the value of enterprise.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.description
     *
     * @param description the value for enterprise.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.question1
     *
     * @return the value of enterprise.question1
     *
     * @mbggenerated
     */
    public String getQuestion1() {
        return question1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.question1
     *
     * @param question1 the value for enterprise.question1
     *
     * @mbggenerated
     */
    public void setQuestion1(String question1) {
        this.question1 = question1 == null ? null : question1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.question2
     *
     * @return the value of enterprise.question2
     *
     * @mbggenerated
     */
    public String getQuestion2() {
        return question2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.question2
     *
     * @param question2 the value for enterprise.question2
     *
     * @mbggenerated
     */
    public void setQuestion2(String question2) {
        this.question2 = question2 == null ? null : question2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.question3
     *
     * @return the value of enterprise.question3
     *
     * @mbggenerated
     */
    public String getQuestion3() {
        return question3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.question3
     *
     * @param question3 the value for enterprise.question3
     *
     * @mbggenerated
     */
    public void setQuestion3(String question3) {
        this.question3 = question3 == null ? null : question3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.question4
     *
     * @return the value of enterprise.question4
     *
     * @mbggenerated
     */
    public String getQuestion4() {
        return question4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.question4
     *
     * @param question4 the value for enterprise.question4
     *
     * @mbggenerated
     */
    public void setQuestion4(String question4) {
        this.question4 = question4 == null ? null : question4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.question5
     *
     * @return the value of enterprise.question5
     *
     * @mbggenerated
     */
    public String getQuestion5() {
        return question5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.question5
     *
     * @param question5 the value for enterprise.question5
     *
     * @mbggenerated
     */
    public void setQuestion5(String question5) {
        this.question5 = question5 == null ? null : question5.trim();
    }

    @Override
    public String toString() {
        return "EnterpriseWithBLOBs{" +
                "description='" + description + '\'' +
                ", question1='" + question1 + '\'' +
                ", question2='" + question2 + '\'' +
                ", question3='" + question3 + '\'' +
                ", question4='" + question4 + '\'' +
                ", question5='" + question5 + '\'' +
                '}';
    }
}