package com.dingzhang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EnterpriseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public EnterpriseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLngIsNull() {
            addCriterion("lng is null");
            return (Criteria) this;
        }

        public Criteria andLngIsNotNull() {
            addCriterion("lng is not null");
            return (Criteria) this;
        }

        public Criteria andLngEqualTo(Double value) {
            addCriterion("lng =", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotEqualTo(Double value) {
            addCriterion("lng <>", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThan(Double value) {
            addCriterion("lng >", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThanOrEqualTo(Double value) {
            addCriterion("lng >=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThan(Double value) {
            addCriterion("lng <", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThanOrEqualTo(Double value) {
            addCriterion("lng <=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngIn(List<Double> values) {
            addCriterion("lng in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotIn(List<Double> values) {
            addCriterion("lng not in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngBetween(Double value1, Double value2) {
            addCriterion("lng between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotBetween(Double value1, Double value2) {
            addCriterion("lng not between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("lat is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("lat is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(Double value) {
            addCriterion("lat =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(Double value) {
            addCriterion("lat <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(Double value) {
            addCriterion("lat >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(Double value) {
            addCriterion("lat >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(Double value) {
            addCriterion("lat <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(Double value) {
            addCriterion("lat <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<Double> values) {
            addCriterion("lat in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<Double> values) {
            addCriterion("lat not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(Double value1, Double value2) {
            addCriterion("lat between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(Double value1, Double value2) {
            addCriterion("lat not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNull() {
            addCriterion("leader is null");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNotNull() {
            addCriterion("leader is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderEqualTo(String value) {
            addCriterion("leader =", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotEqualTo(String value) {
            addCriterion("leader <>", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThan(String value) {
            addCriterion("leader >", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("leader >=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThan(String value) {
            addCriterion("leader <", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThanOrEqualTo(String value) {
            addCriterion("leader <=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLike(String value) {
            addCriterion("leader like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotLike(String value) {
            addCriterion("leader not like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderIn(List<String> values) {
            addCriterion("leader in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotIn(List<String> values) {
            addCriterion("leader not in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderBetween(String value1, String value2) {
            addCriterion("leader between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotBetween(String value1, String value2) {
            addCriterion("leader not between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderIsNull() {
            addCriterion("call_leader is null");
            return (Criteria) this;
        }

        public Criteria andCall_leaderIsNotNull() {
            addCriterion("call_leader is not null");
            return (Criteria) this;
        }

        public Criteria andCall_leaderEqualTo(String value) {
            addCriterion("call_leader =", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderNotEqualTo(String value) {
            addCriterion("call_leader <>", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderGreaterThan(String value) {
            addCriterion("call_leader >", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderGreaterThanOrEqualTo(String value) {
            addCriterion("call_leader >=", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderLessThan(String value) {
            addCriterion("call_leader <", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderLessThanOrEqualTo(String value) {
            addCriterion("call_leader <=", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderLike(String value) {
            addCriterion("call_leader like", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderNotLike(String value) {
            addCriterion("call_leader not like", value, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderIn(List<String> values) {
            addCriterion("call_leader in", values, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderNotIn(List<String> values) {
            addCriterion("call_leader not in", values, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderBetween(String value1, String value2) {
            addCriterion("call_leader between", value1, value2, "call_leader");
            return (Criteria) this;
        }

        public Criteria andCall_leaderNotBetween(String value1, String value2) {
            addCriterion("call_leader not between", value1, value2, "call_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderIsNull() {
            addCriterion("photo_leader is null");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderIsNotNull() {
            addCriterion("photo_leader is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderEqualTo(String value) {
            addCriterion("photo_leader =", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderNotEqualTo(String value) {
            addCriterion("photo_leader <>", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderGreaterThan(String value) {
            addCriterion("photo_leader >", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderGreaterThanOrEqualTo(String value) {
            addCriterion("photo_leader >=", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderLessThan(String value) {
            addCriterion("photo_leader <", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderLessThanOrEqualTo(String value) {
            addCriterion("photo_leader <=", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderLike(String value) {
            addCriterion("photo_leader like", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderNotLike(String value) {
            addCriterion("photo_leader not like", value, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderIn(List<String> values) {
            addCriterion("photo_leader in", values, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderNotIn(List<String> values) {
            addCriterion("photo_leader not in", values, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderBetween(String value1, String value2) {
            addCriterion("photo_leader between", value1, value2, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andPhoto_leaderNotBetween(String value1, String value2) {
            addCriterion("photo_leader not between", value1, value2, "photo_leader");
            return (Criteria) this;
        }

        public Criteria andMemberIsNull() {
            addCriterion("member is null");
            return (Criteria) this;
        }

        public Criteria andMemberIsNotNull() {
            addCriterion("member is not null");
            return (Criteria) this;
        }

        public Criteria andMemberEqualTo(String value) {
            addCriterion("member =", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberNotEqualTo(String value) {
            addCriterion("member <>", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberGreaterThan(String value) {
            addCriterion("member >", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberGreaterThanOrEqualTo(String value) {
            addCriterion("member >=", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberLessThan(String value) {
            addCriterion("member <", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberLessThanOrEqualTo(String value) {
            addCriterion("member <=", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberLike(String value) {
            addCriterion("member like", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberNotLike(String value) {
            addCriterion("member not like", value, "member");
            return (Criteria) this;
        }

        public Criteria andMemberIn(List<String> values) {
            addCriterion("member in", values, "member");
            return (Criteria) this;
        }

        public Criteria andMemberNotIn(List<String> values) {
            addCriterion("member not in", values, "member");
            return (Criteria) this;
        }

        public Criteria andMemberBetween(String value1, String value2) {
            addCriterion("member between", value1, value2, "member");
            return (Criteria) this;
        }

        public Criteria andMemberNotBetween(String value1, String value2) {
            addCriterion("member not between", value1, value2, "member");
            return (Criteria) this;
        }

        public Criteria andCall_memberIsNull() {
            addCriterion("call_member is null");
            return (Criteria) this;
        }

        public Criteria andCall_memberIsNotNull() {
            addCriterion("call_member is not null");
            return (Criteria) this;
        }

        public Criteria andCall_memberEqualTo(String value) {
            addCriterion("call_member =", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberNotEqualTo(String value) {
            addCriterion("call_member <>", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberGreaterThan(String value) {
            addCriterion("call_member >", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberGreaterThanOrEqualTo(String value) {
            addCriterion("call_member >=", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberLessThan(String value) {
            addCriterion("call_member <", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberLessThanOrEqualTo(String value) {
            addCriterion("call_member <=", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberLike(String value) {
            addCriterion("call_member like", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberNotLike(String value) {
            addCriterion("call_member not like", value, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberIn(List<String> values) {
            addCriterion("call_member in", values, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberNotIn(List<String> values) {
            addCriterion("call_member not in", values, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberBetween(String value1, String value2) {
            addCriterion("call_member between", value1, value2, "call_member");
            return (Criteria) this;
        }

        public Criteria andCall_memberNotBetween(String value1, String value2) {
            addCriterion("call_member not between", value1, value2, "call_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberIsNull() {
            addCriterion("photo_member is null");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberIsNotNull() {
            addCriterion("photo_member is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberEqualTo(String value) {
            addCriterion("photo_member =", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberNotEqualTo(String value) {
            addCriterion("photo_member <>", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberGreaterThan(String value) {
            addCriterion("photo_member >", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberGreaterThanOrEqualTo(String value) {
            addCriterion("photo_member >=", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberLessThan(String value) {
            addCriterion("photo_member <", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberLessThanOrEqualTo(String value) {
            addCriterion("photo_member <=", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberLike(String value) {
            addCriterion("photo_member like", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberNotLike(String value) {
            addCriterion("photo_member not like", value, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberIn(List<String> values) {
            addCriterion("photo_member in", values, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberNotIn(List<String> values) {
            addCriterion("photo_member not in", values, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberBetween(String value1, String value2) {
            addCriterion("photo_member between", value1, value2, "photo_member");
            return (Criteria) this;
        }

        public Criteria andPhoto_memberNotBetween(String value1, String value2) {
            addCriterion("photo_member not between", value1, value2, "photo_member");
            return (Criteria) this;
        }

        public Criteria andBossIsNull() {
            addCriterion("boss is null");
            return (Criteria) this;
        }

        public Criteria andBossIsNotNull() {
            addCriterion("boss is not null");
            return (Criteria) this;
        }

        public Criteria andBossEqualTo(String value) {
            addCriterion("boss =", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotEqualTo(String value) {
            addCriterion("boss <>", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossGreaterThan(String value) {
            addCriterion("boss >", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossGreaterThanOrEqualTo(String value) {
            addCriterion("boss >=", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLessThan(String value) {
            addCriterion("boss <", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLessThanOrEqualTo(String value) {
            addCriterion("boss <=", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLike(String value) {
            addCriterion("boss like", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotLike(String value) {
            addCriterion("boss not like", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossIn(List<String> values) {
            addCriterion("boss in", values, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotIn(List<String> values) {
            addCriterion("boss not in", values, "boss");
            return (Criteria) this;
        }

        public Criteria andBossBetween(String value1, String value2) {
            addCriterion("boss between", value1, value2, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotBetween(String value1, String value2) {
            addCriterion("boss not between", value1, value2, "boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossIsNull() {
            addCriterion("call_boss is null");
            return (Criteria) this;
        }

        public Criteria andCall_bossIsNotNull() {
            addCriterion("call_boss is not null");
            return (Criteria) this;
        }

        public Criteria andCall_bossEqualTo(String value) {
            addCriterion("call_boss =", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossNotEqualTo(String value) {
            addCriterion("call_boss <>", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossGreaterThan(String value) {
            addCriterion("call_boss >", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossGreaterThanOrEqualTo(String value) {
            addCriterion("call_boss >=", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossLessThan(String value) {
            addCriterion("call_boss <", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossLessThanOrEqualTo(String value) {
            addCriterion("call_boss <=", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossLike(String value) {
            addCriterion("call_boss like", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossNotLike(String value) {
            addCriterion("call_boss not like", value, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossIn(List<String> values) {
            addCriterion("call_boss in", values, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossNotIn(List<String> values) {
            addCriterion("call_boss not in", values, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossBetween(String value1, String value2) {
            addCriterion("call_boss between", value1, value2, "call_boss");
            return (Criteria) this;
        }

        public Criteria andCall_bossNotBetween(String value1, String value2) {
            addCriterion("call_boss not between", value1, value2, "call_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossIsNull() {
            addCriterion("photo_boss is null");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossIsNotNull() {
            addCriterion("photo_boss is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossEqualTo(String value) {
            addCriterion("photo_boss =", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossNotEqualTo(String value) {
            addCriterion("photo_boss <>", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossGreaterThan(String value) {
            addCriterion("photo_boss >", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossGreaterThanOrEqualTo(String value) {
            addCriterion("photo_boss >=", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossLessThan(String value) {
            addCriterion("photo_boss <", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossLessThanOrEqualTo(String value) {
            addCriterion("photo_boss <=", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossLike(String value) {
            addCriterion("photo_boss like", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossNotLike(String value) {
            addCriterion("photo_boss not like", value, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossIn(List<String> values) {
            addCriterion("photo_boss in", values, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossNotIn(List<String> values) {
            addCriterion("photo_boss not in", values, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossBetween(String value1, String value2) {
            addCriterion("photo_boss between", value1, value2, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andPhoto_bossNotBetween(String value1, String value2) {
            addCriterion("photo_boss not between", value1, value2, "photo_boss");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(Date value) {
            addCriterionForJDBCDate("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(Date value) {
            addCriterionForJDBCDate("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(Date value) {
            addCriterionForJDBCDate("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(Date value) {
            addCriterionForJDBCDate("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<Date> values) {
            addCriterionForJDBCDate("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<Date> values) {
            addCriterionForJDBCDate("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}