package com.dingzhang.model;

import java.util.Date;

public class Enterprise extends EnterpriseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.leader
     *
     * @mbggenerated
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.call_leader
     *
     * @mbggenerated
     */
    private String call_leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.photo_leader
     *
     * @mbggenerated
     */
    private String photo_leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.member
     *
     * @mbggenerated
     */
    private String member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.call_member
     *
     * @mbggenerated
     */
    private String call_member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.photo_member
     *
     * @mbggenerated
     */
    private String photo_member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.boss
     *
     * @mbggenerated
     */
    private String boss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.call_boss
     *
     * @mbggenerated
     */
    private String call_boss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.photo_boss
     *
     * @mbggenerated
     */
    private String photo_boss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public Enterprise(Integer id, Double lng, String name, Double lat, Integer level, String leader, String call_leader, String photo_leader, String member, String call_member, String photo_member, String boss, String call_boss, String photo_boss, Integer type, Date deadline) {
        super(id, lng);
        this.name = name;
        this.lat = lat;
        this.level = level;
        this.leader = leader;
        this.call_leader = call_leader;
        this.photo_leader = photo_leader;
        this.member = member;
        this.call_member = call_member;
        this.photo_member = photo_member;
        this.boss = boss;
        this.call_boss = call_boss;
        this.photo_boss = photo_boss;
        this.type = type;
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    public Enterprise() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.name
     *
     * @return the value of enterprise.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.name
     *
     * @param name the value for enterprise.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.lat
     *
     * @return the value of enterprise.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.lat
     *
     * @param lat the value for enterprise.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.level
     *
     * @return the value of enterprise.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.level
     *
     * @param level the value for enterprise.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.leader
     *
     * @return the value of enterprise.leader
     *
     * @mbggenerated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.leader
     *
     * @param leader the value for enterprise.leader
     *
     * @mbggenerated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.call_leader
     *
     * @return the value of enterprise.call_leader
     *
     * @mbggenerated
     */
    public String getCall_leader() {
        return call_leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.call_leader
     *
     * @param call_leader the value for enterprise.call_leader
     *
     * @mbggenerated
     */
    public void setCall_leader(String call_leader) {
        this.call_leader = call_leader == null ? null : call_leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.photo_leader
     *
     * @return the value of enterprise.photo_leader
     *
     * @mbggenerated
     */
    public String getPhoto_leader() {
        return photo_leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.photo_leader
     *
     * @param photo_leader the value for enterprise.photo_leader
     *
     * @mbggenerated
     */
    public void setPhoto_leader(String photo_leader) {
        this.photo_leader = photo_leader == null ? null : photo_leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.member
     *
     * @return the value of enterprise.member
     *
     * @mbggenerated
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.member
     *
     * @param member the value for enterprise.member
     *
     * @mbggenerated
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.call_member
     *
     * @return the value of enterprise.call_member
     *
     * @mbggenerated
     */
    public String getCall_member() {
        return call_member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.call_member
     *
     * @param call_member the value for enterprise.call_member
     *
     * @mbggenerated
     */
    public void setCall_member(String call_member) {
        this.call_member = call_member == null ? null : call_member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.photo_member
     *
     * @return the value of enterprise.photo_member
     *
     * @mbggenerated
     */
    public String getPhoto_member() {
        return photo_member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.photo_member
     *
     * @param photo_member the value for enterprise.photo_member
     *
     * @mbggenerated
     */
    public void setPhoto_member(String photo_member) {
        this.photo_member = photo_member == null ? null : photo_member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.boss
     *
     * @return the value of enterprise.boss
     *
     * @mbggenerated
     */
    public String getBoss() {
        return boss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.boss
     *
     * @param boss the value for enterprise.boss
     *
     * @mbggenerated
     */
    public void setBoss(String boss) {
        this.boss = boss == null ? null : boss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.call_boss
     *
     * @return the value of enterprise.call_boss
     *
     * @mbggenerated
     */
    public String getCall_boss() {
        return call_boss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.call_boss
     *
     * @param call_boss the value for enterprise.call_boss
     *
     * @mbggenerated
     */
    public void setCall_boss(String call_boss) {
        this.call_boss = call_boss == null ? null : call_boss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.photo_boss
     *
     * @return the value of enterprise.photo_boss
     *
     * @mbggenerated
     */
    public String getPhoto_boss() {
        return photo_boss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.photo_boss
     *
     * @param photo_boss the value for enterprise.photo_boss
     *
     * @mbggenerated
     */
    public void setPhoto_boss(String photo_boss) {
        this.photo_boss = photo_boss == null ? null : photo_boss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.type
     *
     * @return the value of enterprise.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.type
     *
     * @param type the value for enterprise.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.deadline
     *
     * @return the value of enterprise.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.deadline
     *
     * @param deadline the value for enterprise.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    @Override
    public String toString() {
        return "Enterprise{" +
                "name='" + name + '\'' +
                ", lat=" + lat +
                ", level=" + level +
                ", leader='" + leader + '\'' +
                ", call_leader='" + call_leader + '\'' +
                ", photo_leader='" + photo_leader + '\'' +
                ", member='" + member + '\'' +
                ", call_member='" + call_member + '\'' +
                ", photo_member='" + photo_member + '\'' +
                ", boss='" + boss + '\'' +
                ", call_boss='" + call_boss + '\'' +
                ", photo_boss='" + photo_boss + '\'' +
                ", type=" + type +
                ", deadline=" + deadline +
                '}';
    }
}